---
abstract: 'add and override per-object methods'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Extend
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.09
  Storable: 2.05
  perl: 5.008000
resources:
  bugtracker: https://github.com/chocolateboy/Object-Extend/issues
  repository: https://github.com/chocolateboy/Object-Extend
version: v0.4.0
x_test_requires:
  Test::More: 0
